

services:
  postgres:
    image: postgres:15-alpine
    container_name: vantageai_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: market_intelligence
    ports:
      - "5432:5432"
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: